:clients:
  :eth1: geth
  :beacon: prysmbeacon
  :validator: prysmvalidator

:ports:
  :geth: 30303
  :prysm:
    :tcp: 13000
    :udp: 12000

:directories:
  :geth: /var/lib/goethereum

:users:
  :geth: goeth
  :prysm: prysm
