:clients:
  :eth1: geth
  :beacon: prysmbeacon
  :validator: prysmvalidator

:ports:
  :erigon: 30303
  :geth: 30303
  :prysm:
    :tcp: 13000
    :udp: 12000

:directories:
  :geth: /var/lib/goethereum
  :erigon: /var/lib/erigon
  :prysmbeacon: /var/lib/prysm/beacon
  :prysmvalidator: /var/lib/prysm/validator

:executables:
  :geth: geth
  :erigon: erigon
  :prysmbeacon: beacon-chain 
  :prysmvalidator: validator

:users:
  :geth: goeth
  :erigon: erigon
  :prysmbeacon: prysmbeacon
  :prysmvalidator: prysmvalidator

:github:
  :geth: ethereum/go-ethereum
  :erigon: ledgerwatch/erigon
  :prysmbeacon: prysmaticlabs/prysm
  :prysmvalidator: prysmaticlabs/prysm

:sources:
  :prysmbeacon: 
    :url: https://github.com/prysmaticlabs/prysm/releases/download/v1.3.9/
    :parent_url: https://github.com/prysmaticlabs/prysm/releases/download/
    :file: beacon-chain-v1.3.9-linux-amd64
    :prefix: beacon-chain-
    :suffix: -linux-amd64
  :prysmvalidator:
    :url:  https://github.com/prysmaticlabs/prysm/releases/download/v1.3.9/
    :parent_url: https://github.com/prysmaticlabs/prysm/releases/download/
    :file: validator-v1.3.9-linux-amd64 
    :prefix: validator-
    :suffix: -linux-amd64

:geth:
  :minpeercount: 8
  :http_endpoint: http://127.0.0.1:8545
  :cache: 8192
  :maxpeercount: 50

:prysmbeacon:
  :minpeercount: 20
  :http_endpoint: http://127.0.0.1:3500 

:system:
  :services: /etc/systemd/system
  :binaries: /usr/local/bin