:clients:
  :eth1: geth
  :beacon: prysmbeacon
  :validator: prysmvalidator

:ports:
  :geth: 30303
  :prysm:
    :tcp: 13000
    :udp: 12000

:directories:
  :geth:  /media/tfj/blockchains/goethereum/
  :prysmbeacon: /var/lib/prysm/beacon
  :prysmvalidator: /var/lib/prysm/validator

:users:
  :geth: goeth
  :prysm: prysm

:geth:
  :minpeercount: 8
